version: 0.0
os: linux
files:
  - source: /
    destination: /home/root/signal
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: aws_scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_server
      # timeout: 60
      runas: root
