name: learn-github-actions
on:
  push:
    branches:
      - codeDeploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'
    # - run: npm install -g bats
    # - run: bats -v
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
        aws-region: eu-west-2
    - name: Copy files to the production website with the AWS CLI
      run: | 
        rm -rf node_modules
        rm -rf node_modules devops-proxy-server.zip
        zip -r devops-proxy-server.zip .
        aws s3 cp ./devops-proxy-server.zip s3://team2-nodea-pp/



